### ISSUE TITLE
Reenable /v1/user DELETE request

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/StudyBuddy-api#1]
Currently, support for the `DELETE` request has been disabled due to a potential security vulnerability where an attacker can delete a user from the list of authenticated users without explicit acknowledgement from the user.

---

# TODO

- [ ] Implement an authentication system
  - JWT?
  - API key?
  - OAuth token?
- [ ] Reenable `DELETE` request
- [ ] Link to this issue

**Comment by EdricChan03** [comment]
Oopsie! Sorry for closing this issue. :man_shrugging:
